#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for authorized use: this script is part of a project that is
#   distributed under the Apache License, Version 2.0.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for anchoring implicit quotes
# shellcheck disable=SC2086
while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        app_path=$link
    else
        app_path=$(dirname "$app_path")/$link
    fi
done

app_home=$(cd "$(dirname "$app_path")" && pwd)

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$app_home/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        # Others might point to a JRE
        JAVACMD=$JAVA_HOME/bin/java
    elif [ -x "$JAVA_HOME/jre/bin/java" ] ; then
        # Others might point to a JDK
        JAVACMD=$JAVA_HOME/jre/bin/java
    fi
else
    JAVACMD=java
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Collect all arguments for the java command, following the shell's quoting rules.
# shellcheck disable=SC2124
# shellcheck disable=SC2086
set -- "$@"

# For Cygwin, switch paths to Windows format before running java
if $cygwin ; then
    app_home=$(cygpath --path --mixed "$app_home")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    
    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$(cygpath --mixed /)
    # shellcheck disable=SC2001
    ROOTDIRS=$(echo "$ROOTDIRSRAW" | sed 's/[|]/\\|/g')
    # shellcheck disable=SC2001
    PATTERNSRAW=$(echo "$ROOTDIRS" | tr -d '\n' | sed 's/[ ][ ]*/|/g')
    # shellcheck disable=SC2001
    PATTERNS="^($PATTERNSRAW)"
    
    # shellcheck disable=SC2046
    # shellcheck disable=SC2086
    set -- $(for arg do
        if echo "$arg" | grep -E -q "$PATTERNS"; then
            cygpath --mixed "$arg"
        else
            echo "$arg"
        fi
    done)
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' /" ; done
}
# shellcheck disable=SC2128
APP_ARGS=$(save "$@")

# Execute Gradle
# shellcheck disable=SC2086
exec "$JAVACMD" \
    "-Dorg.gradle.appname=$0" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    $APP_ARGS
